# Generated by Django 6.0.5 on 2026-06-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='會員帳號')),
                ('last_name', models.CharField(max_length=20, verbose_name='姓氏')),
                ('first_name', models.CharField(max_length=30, verbose_name='名字')),
                ('password', models.CharField(max_length=128, verbose_name='密碼')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='電子信箱')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='電話號碼')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('gender', models.CharField(blank=True, choices=[('M', '男'), ('F', '女'), ('O', '其他')], max_length=1, null=True, verbose_name='性別')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='註冊時間')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(default='dishes/default.jpg', upload_to='dishes/')),
                ('spicy_level', models.IntegerField(default=0, verbose_name='辣度等級')),
                ('description', models.TextField(blank=True, null=True, verbose_name='介紹')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='主廚推薦')),
                ('category', models.CharField(choices=[('appetizer', '開胃菜'), ('meat', '肉類'), ('seafood', '海鮮'), ('vegetarian', '素食'), ('soup', '湯品'), ('dessert', '甜點'), ('rice_and_noodles', '飯類和麵類'), ('egg_and_tofu', '蛋類和豆腐類')], default='all', max_length=20, verbose_name='網頁分類標籤')),
            ],
            options={
                'verbose_name': '菜色',
                'verbose_name_plural': '菜單管理',
            },
        ),
    ]
