# Generated by Django 6.0.5 on 2026-06-17 07:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(default='dishes/default.jpg', upload_to='dishes/')),
                ('spicy_level', models.IntegerField(default=0, verbose_name='辣度等級')),
                ('description', models.TextField(blank=True, null=True, verbose_name='介紹')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='主廚推薦')),
                ('is_available', models.BooleanField(default=True, verbose_name='是否供應')),
                ('category', models.CharField(choices=[('appetizer', '開胃菜'), ('meat', '肉類'), ('seafood', '海鮮'), ('vegetarian', '素食'), ('soup', '湯品'), ('dessert', '甜點'), ('rice_and_noodles', '飯類和麵類'), ('egg_and_tofu', '蛋類和豆腐類')], default='all', max_length=20, verbose_name='網頁分類標籤')),
            ],
            options={
                'verbose_name': '菜色',
                'verbose_name_plural': '菜單管理',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='餐點名稱')),
                ('price', models.IntegerField(verbose_name='價格')),
                ('is_available', models.BooleanField(default=True, verbose_name='是否供應')),
            ],
        ),
        migrations.CreateModel(
            name='CustomMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='會員帳號')),
                ('last_name', models.CharField(max_length=20, verbose_name='姓氏')),
                ('first_name', models.CharField(max_length=30, verbose_name='名字')),
                ('password', models.CharField(max_length=128, verbose_name='密碼')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='電子信箱')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='電話號碼')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('gender', models.CharField(blank=True, choices=[('M', '男'), ('F', '女'), ('O', '其他')], max_length=1, null=True, verbose_name='性別')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='註冊時間')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用狀態')),
                ('is_staff', models.BooleanField(default=False, verbose_name='後台登入權限')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'myapp_custommember',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='數量')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='會員')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.dish', verbose_name='餐點')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.IntegerField(verbose_name='總金額')),
                ('status', models.CharField(choices=[('pending', '未付款'), ('paid', '已付款/準備中'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='頂單狀態')),
                ('merchant_trade_no', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('pickup_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='預約取餐時間')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='會員')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100, verbose_name='餐點名稱(快照)')),
                ('price', models.IntegerField(verbose_name='購買時價格')),
                ('quantity', models.PositiveIntegerField(verbose_name='數量')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myapp.order', verbose_name='訂單')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='訂位人姓名')),
                ('phone', models.CharField(max_length=15, verbose_name='聯絡電話')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='電子信箱')),
                ('date', models.DateField(verbose_name='訂位日期')),
                ('time_slot', models.CharField(max_length=10, verbose_name='用餐時段')),
                ('guests', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='用餐人數')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='填單時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='關聯會員')),
            ],
            options={
                'verbose_name': '線上訂位',
                'verbose_name_plural': '線上訂位管理',
                'ordering': ['-date', 'time_slot'],
            },
        ),
    ]
