# Generated by Django 6.0.5 on 2026-06-10 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='餐點名稱')),
                ('price', models.IntegerField(verbose_name='價格')),
                ('is_available', models.BooleanField(default=True, verbose_name='是否供應')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='數量')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.custommember', verbose_name='會員')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.menuitem', verbose_name='餐點')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, verbose_name='訂單時間')),
                ('total_amount', models.IntegerField(verbose_name='總金額')),
                ('status', models.CharField(choices=[('pending', '未付款'), ('paid', '已付款/準備中'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='頂單狀態')),
                ('merchant_trade_no', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.custommember', verbose_name='會員')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100, verbose_name='餐點名稱(快照)')),
                ('price', models.IntegerField(verbose_name='購買時價格')),
                ('quantity', models.PositiveIntegerField(verbose_name='數量')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myapp.order', verbose_name='訂單')),
            ],
        ),
    ]
