# Generated by Django 6.0.5 on 2026-06-03 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_dish_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='spicy_level',
            field=models.IntegerField(default=0, verbose_name='辣度等級'),
        ),
    ]
