# Generated by Django 6.0.5 on 2026-06-10 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_menuitem_cartitem_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='是否供應'),
        ),
    ]
