# Generated by Django 6.0.6 on 2026-06-23 06:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_reservation_is_arrived_alter_cartitem_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('INCOME', '總收入'), ('EXPENSE', '總支出')], max_length=10, verbose_name='收支大類')),
                ('name', models.CharField(max_length=50, verbose_name='科目名稱（如：海鮮類/肉品類/員工獎金/水電瓦斯）')),
            ],
            options={
                'verbose_name': '財務科目分類',
                'verbose_name_plural': '1. 財務科目分類管理',
            },
        ),
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金額')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='記帳日期')),
                ('note', models.TextField(blank=True, null=True, verbose_name='詳細備註（可寫食材細項、員工姓名）')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.financialcategory', verbose_name='款項科目')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.order', verbose_name='關聯點餐訂單')),
            ],
            options={
                'verbose_name': '財務收支紀錄',
                'verbose_name_plural': '2. 財務收支流水帳',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
