# Generated by Django 6.0.5 on 2026-06-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_dish_spicy_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='category',
            field=models.CharField(choices=[('appetizer', '開胃菜'), ('meat', '肉類'), ('seafood', '海鮮')], default='all', max_length=20, verbose_name='網頁分類標籤'),
        ),
    ]
