# Generated by Django 6.0.5 on 2026-06-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_dish_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.CharField(choices=[('appetizer', '開胃菜'), ('meat', '肉類'), ('seafood', '海鮮'), ('vegetarian', '素食'), ('soup', '湯品'), ('dessert', '甜點'), ('rice and noodles', '飯類和麵類')], default='all', max_length=20, verbose_name='網頁分類標籤'),
        ),
    ]
