# Generated by Django 6.0.5 on 2026-06-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_dish_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name': '菜色', 'verbose_name_plural': '菜單管理'},
        ),
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.CharField(choices=[('appetizer', '開胃菜'), ('meat', '肉類'), ('seafood', '海鮮'), ('vegetarian', '素食'), ('soup', '湯品'), ('dessert', '甜點'), ('rice_and_noodles', '飯類和麵類'), ('egg_and_tofu', '蛋類和豆腐類')], default='all', max_length=20, verbose_name='網頁分類標籤'),
        ),
    ]
