# Generated by Django 6.0.5 on 2026-06-04 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_dish_options_alter_dish_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='is_recommended',
            field=models.BooleanField(default=False, verbose_name='主廚推薦'),
        ),
    ]
